services:
  elasticsearch:
    image: elasticsearch:8.17.1
    container_name: es
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=123456
      - ES_JAVA_OPTS=-Xms128m -Xmx128m # 出現 error code exit(137) 加此行
         # 開發測試用，關閉 SSL
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      # - "logger.level=DEBUG"
    networks:
      - elastic
  kibana:
    image: kibana:8.17.1
    container_name: kibana
    ports:
      - "5601:5601"
    # volumes:
    #   - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - ELASTICSEARCH_HOSTS="http://elasticsearch:9200"
      # - XPACK_SECURITY_ENABLED=false
      # 創建一個專門的 Kibana 系統用戶
      - ELASTICSEARCH_USERNAME=kibana_system
    depends_on:
      - elasticsearch
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
